[package]
name = 'curies-r'
publish = false
version = '0.3.0'
edition = '2021'
license-file.workspace = true

[lib]
crate-type = [ 'staticlib' ]
name = 'curies'

[dependencies]
curies.workspace = true
extendr-api = '0.6.0'
tokio = { version = "1.34", features = ["rt-multi-thread"] }
