
name: Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clippy:
    name: 📎 fmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: rustup update
      - run: cargo fmt -- --check
      - run: cargo clippy --all --all-targets --all-features
      # - run: cargo deny check

  test-rust:
    name: 🧪 Test Rust
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: cargo build --all-features
      - run: cargo test
        env:
          RUST_BACKTRACE: 1

  cov-rust:
    name: ☂️ Test with coverage Rust
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - name: Generate code coverage
        run: bash ./scripts/cov.sh

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          # fail_ci_if_error: false


  test-js:
    name: 🟨 Test JavaScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          cache-dependency-path: "./js/package.json"
      - run: rustup update && cargo install wasm-pack
      - name: Run tests
        run: ./scripts/test-js.sh

  test-python:
    name: 🐍 Test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: rustup update
      - name: Run tests
        run: ./scripts/test-python.sh

  # TODO: Error in loadNamespace(x) : there is no package called ‘devtools’
  # test-r:
  #   name: 📈 Test R
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: r-lib/actions/setup-r@v2
  #     - run: rustup update
  #     - name: Run tests
  #       run: ./scripts/test-r.sh --install

  docs:
    name: 📚 Update docs website
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r lib/docs/requirements.txt

      - name: Deploy mkdocs on GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs build -f lib/docs/mkdocs.yml -d dist
        # mkdocs gh-deploy dont support new pages

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './lib/docs/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
